name: Version Update Workflow

on:
  push:
    branches:
      - main

jobs:
  check-version:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Get Previous Version
      id: previous_version
      run: echo "::set-output name=version::$(git show HEAD~1:package.json | grep -oP '(?<="version": ")[^"]+')"

    - name: Get Current Version
      id: current_version
      run: echo "::set-output name=version::$(grep -oP '(?<="version": ")[^"]+' package.json)"

    - name: Compare Versions
      id: compare_versions
      run: echo "::set-output name=changed::$(test ${{ steps.previous_version.outputs.version }} != ${{ steps.current_version.outputs.version }});"

    - name: Trigger On Version Change
      if: steps.compare_versions.outputs.changed == 'true'
      run: |
        echo "A new version of package.json was pushed!"
        # Add your actual workflow steps here
